import assert from "node:assert/strict";
import { currentApplicationCorneaExample } from "../shared/clinical/cornea-data.example";
import { createRadialPlacidoObservation } from "../shared/clinical/placido/placido-observation";
import { placidoCalibrationSchema, syntheticSphereFixture } from "../shared/clinical/placido/placido-calibration";

const observation = createRadialPlacidoObservation(512, 512, 256, 255, [12, 24, 36]);
assert.equal(observation.calibrationStatus, "UNCALIBRATED"); assert.equal(observation.detectedCenter.unit, "px"); assert.equal(observation.rings[0].observedRadius, 12); assert.equal(observation.rings[0].unit, "px"); assert.equal(observation.rings[0].meridianAngle.status, "unavailable"); assert.equal(observation.rings[0].targetCorrespondence.status, "unresolved"); assert.equal(observation.rings[2].detectedRingIndex, 2); assert.equal(observation.provenance.algorithm?.includes("ring detection"), true); assert.deepEqual(JSON.parse(JSON.stringify(observation)), observation);
const sphere = syntheticSphereFixture(7.5); assert.equal(sphere.radius.unit, "mm"); assert.equal(sphere.radius.value, 7.5); assert.equal(sphere.provenance.origin, "reference"); assert.deepEqual(JSON.parse(JSON.stringify(sphere)), sphere);
const missingCalibration = { schemaVersion: "1.0", provenance: sphere.provenance, device: { ringCount: { status: "unavailable", reason: "not supplied" }, ringRadii: { status: "unavailable", reason: "not supplied" }, targetGeometry: { status: "unavailable", reason: "not supplied" }, cameraToTarget: { status: "unavailable", reason: "not supplied" }, opticalAxis: { status: "unavailable", reason: "not supplied" } }, camera: { imageDimensions: { status: "available", value: { widthPx: 512, heightPx: 512 } }, principalPoint: { status: "unavailable", reason: "not supplied" }, focalLength: { status: "unavailable", reason: "not supplied" }, distortionModel: { status: "unavailable", reason: "not supplied" } }, acquisition: { workingDistance: { status: "available", value: { value: 75, unit: "mm" } }, alignment: { status: "unavailable", reason: "not supplied" }, referenceCenter: { status: "available", value: { x: 256, y: 255, unit: "px" } } }, calibrationSurface: { status: "available", value: sphere } };
assert.ok(placidoCalibrationSchema.parse(missingCalibration)); assert.equal(currentApplicationCorneaExample.anteriorSurface.status, "unavailable"); assert.throws(() => createRadialPlacidoObservation(512, 512, 256, 256, [Number.NaN])); assert.throws(() => createRadialPlacidoObservation(512, 512, 256, 256, [-1]));
console.log("Placido calibration foundation tests passed (16 assertions).");

